[project]
name = "app"
version = "0.0.1"
description = "api for project one"
dependencies = [
    "flask",
    "flask-cors"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"