DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  tokens INTEGER NOT NULL CHECK(tokens >= 0) DEFAULT 0,
  tons INTEGER NOT NULL CHECK(tons >= 0) DEFAULT 0
);