DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS pc;
DROP TABLE IF EXISTS ai;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  tokens INTEGER NOT NULL CHECK(tokens >= 0) DEFAULT 0,
  tons INTEGER NOT NULL CHECK(tons >= 0) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pc (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  ai_id INTEGER,
  rarity INTEGER NOT NULL,
  is_activated BOOLEAN NOT NULL DEFAULT false,
  health INTEGER NOT NULL DEFAULT 100,
  is_free BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS ai (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  rarity INTEGER NOT NULL
);